services:
  eapteka_timer:
    network_mode: "host"
    environment:
      - TZ=Europe/Moscow
    image: imediadev/eapteka_timer
    user: "1002:1002"
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - /home/main_ftp_user/scripts/eapteka_timer/media:/app/media

